### ISSUE TITLE
Article Template - add title to header

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#252]
- header is missing on article template. should be the same as mock ups

**Comment by camelburrito** [comment]
i assume this was fixed @spacedino re-open if needed

**Comment by ericlindley-g** [comment]
Still missing :)

<img width="381" alt="screen shot 2017-06-26 at 5 27 04 pm" src="https://user-images.githubusercontent.com/16807766/27565706-bd3a2092-5a94-11e7-896a-faacfd6f7887.png">


v. 

<img width="321" alt="screen shot 2017-06-26 at 5 27 11 pm" src="https://user-images.githubusercontent.com/16807766/27565708-bf8ea854-5a94-11e7-9a74-85788df05080.png">

**Comment by eduardogoncalves** [comment]
Remember to update screenshot https://amp.dev/documentation/templates/

this is the imagem file: https://amp.dev/static/img/templates/simple_article.jpg

![image](https://user-images.githubusercontent.com/4308648/58525160-b00a7c00-8198-11e9-83f0-fe4df6072d27.png)
